config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :products
  resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_one :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company

  validates :name, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def index
    @companies = Company.all

    @companies
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path, notice: 'Produto criado com sucesso'
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])

    @company
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to companies_path, notice: 'Empresa editado com sucesso'
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])

    if @company.destroy
      redirect_to companies_path, notice: 'Empresa deletado com sucesso'
    else
      redirect_to companies_path, alert: 'Ops, algum problema ocorreu'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all

    @products
  end

  def show
    @product = Product.find(params[:id])

    @product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Produto criado com sucesso'
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])

    @product
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product, notice: 'Produto editado com sucesso'
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.destroy
      redirect_to products_path, notice: 'Produto deletado com sucesso'
    else
      redirect_to products_path, alert: 'Ops, algum problema ocorreu'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :company_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for @company do |f| %>

  <% if @company.errors.any? %>
    <ul>
      <% @company.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.input :name %>

  <%= f.submit %>
<% end %>

app/views/companies/edit.html.erb
<h1>Editar empresa</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Empresas</h1>

<table class="table">
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to "Deletar", company, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Criar empresa", new_company_path  %>
</p>

app/views/companies/new.html.erb
<h1>Nova empresa</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CRM</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Produtos", root_path %>
            </li>
            <li>
              <%= link_to "Empresas", companies_path %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <% if flash[:notice] || flash[:alert] %>
        <div class="alert <%= flash[:notice] ? 'alert-success' : 'alert-danger' %>">
          <%= flash[:notice] || flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>

  <% if @product.errors.any? %>
    <ul>
      <% @product.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.input :name %>
  <%= f.input :company_id, collection: Company.all, value_method: :id, label: "Empresa", include_blank: true %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Produtos</h1>

<table class="table">
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, product %></td>
      <td><%= product.company.name if product.company %></td>
      <td><%= link_to "Editar", edit_product_path(product) %></td>
      <td><%= link_to "Deletar", product, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Criar produto", new_product_path  %>
</p>

app/views/products/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <%= @product.description %>
</p>

<%= link_to "Voltar para a lista", products_path %>